apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: guestbook-ui
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  type: LoadBalancer
